### ISSUE TITLE
Code does not support the openapi "Tags" feature

### ISSUE THREAD

**Issue by Jeff-Lowrey** [tamasfe/taplo#636]
When I try to use this extension to work with an OpenAPI document version 3.0.3

It produces 

```
simple_openapi_client\parser.py", line 20, in parse_openapi
    return Document(**content)
           ^^^^^^^^^^^^^^^^^^^s
TypeError: Document.__init__() got an unexpected keyword argument 'tags'

```

**Example**
```  
"tags": [
    {
      "name": "XYZ API",
      "description": "API operations for the XYZ System."
    },
    {
      "name": "PDQ",
      "description": "API operations the PDQ System."
    }
  ],
  "paths": {
...  
```

**Comment by Jeff-Lowrey** [comment]
I have at least a somewhat working implementation at
https://github.com/Jeff-Lowrey/openapi-client/tree/working-tags

**Comment by panekj** [comment]
That's not a taplo issue, we do not use Python.

**Comment by Jeff-Lowrey** [comment]
Sorry about that.Posted to the wrong repoOn Jul 18, 2024, at 11:08 AM, Jakub Panek ***@***.***> wrote:﻿
Closed #636 as not planned.
